{
  "hash": "9606d18dc3cbb054ea4a2ebd1d484d88",
  "result": {
    "markdown": "---\ntitle: \"Predicting Employee Attrition\"\nauthor: \"Karol Orozco\"\ndate: \"2022-12\"\n---\n\n\n## 1. Background\n\nYou work for the human capital department of a large corporation. The Board is worried about the relatively high turnover, and your team must look into ways to reduce the number of employees leaving the company. The team needs to understand better the situation, which employees are more likely to leave, and why. Once it is clear what variables impact employee churn, you can present your findings along with your ideas on how to attack the problem.\n\n#### Your challenge\n\nCreate a report that covers the following:\n\n-   Which designation has the highest employee turnover? Which one has the lowest?\n-   Investigate which variables seem to be better predictors of employee departure.\n-   What recommendations would you make regarding ways to reduce employee turnover?\n\n## 2. Get the Data\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n  X     MMM.YY Emp_ID Age Gender City Education_Level Salary Dateofjoining\n1 1 2016-01-01      1  28   Male  C23          Master  57387    2015-12-24\n2 2 2016-02-01      1  28   Male  C23          Master  57387    2015-12-24\n3 3 2016-03-01      1  28   Male  C23          Master  57387    2015-12-24\n4 4 2017-11-01      2  31   Male   C7          Master  67016    2017-11-06\n5 5 2017-12-01      2  31   Male   C7          Master  67016    2017-11-06\n6 6 2016-12-01      4  43   Male  C13          Master  65603    2016-12-07\n  LastWorkingDate Joining.Designation Designation Total.Business.Value\n1            <NA>                   1           1              2381060\n2            <NA>                   1           1              -665480\n3      2016-03-11                   1           1                    0\n4            <NA>                   2           2                    0\n5            <NA>                   2           2                    0\n6            <NA>                   2           2                    0\n  Quarterly.Rating\n1                2\n2                2\n3                2\n4                1\n5                1\n6                1\n```\n:::\n:::\n\n\n#### The variables are defined as follow:\n\n- MMMM-YY:  Reporting Date (Monthly)\n\n- Emp_ID: Unique id for employees\n\n- Age: ge of the employee\n\n- Gender: Gender of the employee\n\n- City: City Code of the employee\n\n- Education_Level: Education level : Bachelor, Master or College\n\n- Salary: Salary of the employee\n\n- Dateofjoining: Joining date for the employee\n\n- LastWorkingDate: Last date of working for the employee\n\n- Joining Designation: Designation of the employee at the time of joining\n\n- Designation: Designation of the employee at the time of reporting\n\n- TotalBusinessValue: The total business value acquired by the employee in a month (negative business indicates cancellation/refund of sold insurance policies)\n\n- Quarterly Rating: Quarterly rating of the employee: 1,2,3,4 (higher is better)\n\n## 3. Prepare and Analyze the Data\n\n- This dataset contains 19104 obs. of  13 variables. We see some duplicate Employees ID, and we should remove them \n\n\n::: {.cell}\n\n:::\n\n\nNow we have 2,381 rows\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n      X                 MMM.YY              Emp_ID               Age       \n Length:2381        Min.   :2016-01-01   Length:2381        Min.   :21.00  \n Class :character   1st Qu.:2016-01-01   Class :character   1st Qu.:29.00  \n Mode  :character   Median :2016-07-01   Mode  :character   Median :33.00  \n                    Mean   :2016-08-29                      Mean   :33.09  \n                    3rd Qu.:2017-05-01                      3rd Qu.:37.00  \n                    Max.   :2017-12-01                      Max.   :58.00  \n                                                                           \n    Gender         City           Education_Level     Salary      \n Female: 977   Length:2381        Bachelor:795    Min.   : 10747  \n Male  :1404   Class :character   College :784    1st Qu.: 39104  \n               Mode  :character   Master  :802    Median : 55276  \n                                                  Mean   : 59209  \n                                                  3rd Qu.: 75765  \n                                                  Max.   :188418  \n                                                                  \n Dateofjoining        LastWorkingDate      Joining.Designation Designation\n Min.   :2010-04-01   Min.   :2015-12-31   1:1026              1:751      \n 1st Qu.:2015-06-29   1st Qu.:2016-01-07   2: 815              2:866      \n Median :2016-07-21   Median :2016-01-19   3: 493              3:611      \n Mean   :2016-02-08   Mean   :2016-03-12   4:  36              4:132      \n 3rd Qu.:2017-05-02   3rd Qu.:2016-01-26   5:  11              5: 21      \n Max.   :2017-12-28   Max.   :2017-12-18                                  \n                      NA's   :2279                                        \n Total.Business.Value Quarterly.Rating\n Min.   :-1590270     1:1649          \n 1st Qu.:       0     2: 411          \n Median :       0     3: 216          \n Mean   :  291175     4: 105          \n 3rd Qu.:  250590                     \n Max.   :10398160                     \n                                      \n```\n:::\n:::\n\n\n- The median age is 33 years old\n\n-   Now, we need to know that in order to predict if the employee will leave the company or not can be best predicted if we have last working day info available and hence although the missing percentage is high, it's not because of Null values but the employees are not planning to leave the company and hence have not provided the info.Therefore we should not remove this feature from our data, instead we need to treat this as our target variable.\n\n- Salary goes from 10747 to 188418 dollars\n\n- Most of the employees have a Master degree\n\n\n::: {.cell}\n\n```{.r .cell-code}\nempl_churn <- empl_turnover %>% mutate(Churn=  ifelse(is.na(LastWorkingDate), \"No\", \"Yes\"))\n\nempl_churn$Churn.Numeric <- as.numeric(as.factor(empl_churn$Churn))-1\n\nglimpse(empl_churn)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 2,381\nColumns: 16\n$ X                    <chr> \"1\", \"4\", \"6\", \"11\", \"14\", \"19\", \"22\", \"23\", \"29\"…\n$ MMM.YY               <date> 2016-01-01, 2017-11-01, 2016-12-01, 2016-01-01, …\n$ Emp_ID               <chr> \"1\", \"2\", \"4\", \"5\", \"6\", \"8\", \"11\", \"12\", \"13\", \"…\n$ Age                  <int> 28, 31, 43, 29, 31, 34, 28, 35, 29, 39, 30, 42, 2…\n$ Gender               <fct> Male, Male, Male, Male, Female, Male, Female, Mal…\n$ City                 <chr> \"C23\", \"C7\", \"C13\", \"C9\", \"C11\", \"C2\", \"C19\", \"C2…\n$ Education_Level      <fct> Master, Master, Master, College, Bachelor, Colleg…\n$ Salary               <int> 57387, 67016, 65603, 46368, 78728, 70656, 42172, …\n$ Dateofjoining        <date> 2015-12-24, 2017-11-06, 2016-12-07, 2016-01-09, …\n$ LastWorkingDate      <date> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, …\n$ Joining.Designation  <fct> 1, 2, 2, 1, 3, 3, 1, 1, 1, 3, 2, 1, 1, 3, 1, 1, 1…\n$ Designation          <fct> 1, 2, 2, 1, 3, 3, 1, 1, 4, 3, 2, 1, 1, 3, 1, 1, 2…\n$ Total.Business.Value <int> 2381060, 0, 0, 0, 0, 0, 0, 500000, 250000, 0, 346…\n$ Quarterly.Rating     <fct> 2, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 2, 1, 1, 4, 2, 2…\n$ Churn                <chr> \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"No\", \"…\n$ Churn.Numeric        <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n```\n:::\n:::\n\n\n\n#### Turnover\n\nNumber of employees that left the company:\n\nThe overall attrition rate in the company in average is 4.28%, which means that 102 employees have left the company during 2016-2017.``\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(empl_churn$Churn)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  No  Yes \n2279  102 \n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(empl_churn,aes(x = Churn, group = Gender)) + \n    geom_bar(aes(y = ..prop.., fill = factor(..x..)), \n    stat=\"count\", color = \"black\", alpha = 0.7) +\n  \n    geom_text(aes(label = scales::percent(..prop..),\n    y= ..prop.. ), stat= \"count\", position = position_stack(vjust = 0.5), size = 4.5) +\n  \n    facet_grid(~Gender) +\n  \n    scale_y_continuous(labels = scales::percent)+\n\n    guides(fill = F)+\n    labs(\n    x = \"Left\", y = \"Percentage\",\n    title=\"Turnover Proportion by Gender\")+\n   scale_fill_manual(values=c(\"gray\", \"#2166AC\"))+\n    theme(text = element_text(size = 12), \n    plot.title = element_text(hjust = 0.5), \n    title = element_text(size = 12))+\n\n\n ggpubr::theme_pubclean()\n```\n\n::: {.cell-output-display}\n![](Analyzing-Employee-Turnover_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\nThere is a small difference in the proportion of women and men that left the company. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nempl_turnover_prop <- empl_churn %>% \n  tabyl(Designation, Churn) %>%\n  adorn_percentages(\"row\") \nkable(empl_turnover_prop,  caption = \"Designation vs Attrition\")\n```\n\n::: {.cell-output-display}\nTable: Designation vs Attrition\n\n|Designation |        No|       Yes|\n|:-----------|---------:|---------:|\n|1           | 0.9227696| 0.0772304|\n|2           | 0.9607390| 0.0392610|\n|3           | 0.9852700| 0.0147300|\n|4           | 1.0000000| 0.0000000|\n|5           | 0.9523810| 0.0476190|\n:::\n:::\n\n-   The data shows that Destination 1 and 5 has the highest employee turnover rate, destination 4 and 3 has the lowest rate.\n\n#### Attrition vs Age\n\nThe majority of employees that left the organization are in their 30's , and the proportion steadily declined.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n### Age vs Turnover\n\n\nempl_churn %>%\ngroup_by(Age, Churn)%>%\nggplot(aes(x = Age, fill = Churn)) +\ngeom_histogram(bins = 30L) +\n\nscale_fill_manual(values=c(\"gray\", \"#2166AC\"))+\n\n ggpubr::theme_pubclean()+\n\n\n  labs( x= \"Age\",\n        y= \"Number of Employees\",\n        title = \"Attrition vs Age\")+\n\ntheme(plot.title = element_text(size =12, face = \"bold\", hjust = 0.45),\nlegend.position=\"bottom\")\n```\n\n::: {.cell-output-display}\n![](Analyzing-Employee-Turnover_files/figure-html/unnamed-chunk-8-1.png){width=1440}\n:::\n:::\n\n\n\n## Education vs Churn\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresult <- compare_props(\n  empl_churn, \n  var1 = \"Education_Level\", \n  var2 = \"Churn\", \n  levs = \"No\", \n  comb = \"Bachelor:College\"\n)\nsummary(result, show = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nPairwise proportion comparisons\nData      : empl_churn \nVariables : Education_Level, Churn \nLevel     : No in Churn \nConfidence: 0.95 \nAdjustment: None \n\n Education_Level  No Yes     p   n n_missing    sd    se    me\n        Bachelor 766  29 0.964 795         0 0.187 0.007 0.013\n         College 740  44 0.944 784         0 0.230 0.008 0.016\n          Master 773  29 0.964 802         0 0.187 0.007 0.013\n\n Null hyp.            Alt. hyp.                       diff p.value  \n Bachelor = College   Bachelor not equal to College   0.02 0.063   .\n\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n\n```{.r .cell-code}\nplot(result, plots = \"dodge\", custom = TRUE)+\n\nscale_fill_manual(values=c(\"gray\", \"#2166AC\"))+\n\n ggpubr::theme_pubclean()+\n\n\n  labs( x= \" \",\n        y= \"% of Churn\",\n        title = \"Attrition vs Education\")+\n\ntheme(plot.title = element_text(size =12, face = \"bold\", hjust = 0.45),\nlegend.position=\"bottom\")\n```\n\n::: {.cell-output-display}\n![](Analyzing-Employee-Turnover_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n- Employees with College degree have the highest number of people living the company\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(corrplot)\nGGally::ggpairs(empl_churn[, unlist(lapply(empl_churn, is.numeric))]) \n```\n\n::: {.cell-output-display}\n![](Analyzing-Employee-Turnover_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\n## 4. The Model- Binary Logistic regression for churn prediction\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(empl_churn) +\n aes(x = Salary, y = Churn, fill = Churn) +\n geom_boxplot() +\nscale_fill_manual(values=c(\"gray\", \"#2166AC\"))+\n ggpubr::theme_pubclean()\n```\n\n::: {.cell-output-display}\n![](Analyzing-Employee-Turnover_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n",
    "supporting": [
      "Analyzing-Employee-Turnover_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}