project:
  type: website
  output-dir: docs

website:
  title: "Portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: Zephyr
    css: styles.css
    code-fold: true
    code-summary: "Show the code"

editor: visual

