---
title: "Employee Churn- Survival Analysis"
author: "Karol Orozco"
date: "2022-10-04"
---

## 1. Introduction

## 2. Import Libraries

```{r, echo=FALSE}
library(tidyverse)
library(ggplot2)
library(survival)
library(skimr)

```

## 3. Load and Prepare the Data

This data set came from Kaggle

```{r}
employee.att <- read.csv("C:/Users/karol/Desktop/Portfolio/DATASET/IBM-HR-Employee-Attrition.csv")
```

Let's take a look at the data:

```{r}
head(employee.att)
names(employee.att)
```

This data set contains 1470 observations and 35 variables. However, for this analysis, I am interested in the following fields:

```{r}
empl.att <- employee.att %>%
  dplyr:::select.data.frame("Attrition", "Department", "Age", "Gender", "MaritalStatus", "DistanceFromHome", "JobSatisfaction", "JobLevel", "YearsAtCompany", "YearsSinceLastPromotion", "OverTime", "MonthlyIncome")

names(empl.att)
```

```{r}
skim(empl.att)
```

#### Convert Variables

## 4. Exploratory Data Analysis


## 5. Survival Model


## 6. Conclusion and Recomendations


