{
  "hash": "489a86770968b3c2e402a914758348e0",
  "result": {
    "markdown": "---\ntitle: \"Analyzing Employee Turnover\"\nauthor: \"Karol Orozco\"\ndate: \"2022-10\"\n---\n\n\n## 1. Background\n\nYou work for the human capital department of a large corporation. The Board is worried about the relatively high turnover, and your team must look into ways to reduce the number of employees leaving the company. The team needs to understand better the situation, which employees are more likely to leave, and why. Once it is clear what variables impact employee churn, you can present your findings along with your ideas on how to attack the problem.\n\n#### Your challenge\n\nCreate a report that covers the following:\n\n-   Which department has the highest employee turnover? Which one has the lowest?\n-   Investigate which variables seem to be better predictors of employee departure.\n-   What recommendations would you make regarding ways to reduce employee turnover?\n\n## 2. Import Libraries\n\n- library(tidyverse) \n- library(ggplot2)\n- library(skimr)\n- library(janitor)\n- library(knitr)\n- library(radiant)\n- library(colorspace)\n- library(gridExtra)\n- library(jtools)\n- library(rpart)\n- library(rpart.plot)\n- library(stargazer)\n\n\n\n\n\n\n\n## 3. Prepare and Analyze the Data\n\nThe department has assembled data on almost 10,000 employees. The team used information from exit interviews, performance reviews, and employee records.\n\n\n::: {.cell}\n\n:::\n\n\nThe variables are defined as follow:\n\n-   \"department\" - the department the employee belongs to.\n-   \"promoted\" - 1 if the employee was promoted in the previous 24 months, 0 otherwise.\n-   \"review\" - the composite score the employee received in their last evaluation.\n-   \"projects\" - how many projects the employee is involved in.\n-   \"salary\" - for confidentiality reasons, salary comes in three tiers: low, medium, high.\n-   \"tenure\" - how many years the employee has been at the company.\n-   \"satisfaction\" - a measure of employee satisfaction from surveys.\n-   \"bonus\" - 1 if the employee received a bonus in the previous 24 months, 0 otherwise.\n-   \"avg_hrs_month\" - the average hours the employee worked in a month.\n-   \"left\" - \"yes\" if the employee ended up leaving, \"no\" otherwise.\n\n\n::: {.cell}\n::: {.cell-output-display}\nTable: Data summary\n\n|                         |              |\n|:------------------------|:-------------|\n|Name                     |empl_turnover |\n|Number of rows           |9540          |\n|Number of columns        |10            |\n|_______________________  |              |\n|Column type frequency:   |              |\n|character                |3             |\n|numeric                  |7             |\n|________________________ |              |\n|Group variables          |None          |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|department    |         0|             1|   2|  11|     0|       10|          0|\n|salary        |         0|             1|   3|   6|     0|        3|          0|\n|left          |         0|             1|   2|   3|     0|        2|          0|\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|   mean|   sd|     p0|    p25|    p50|    p75|   p100|hist  |\n|:-------------|---------:|-------------:|------:|----:|------:|------:|------:|------:|------:|:-----|\n|promoted      |         0|             1|   0.03| 0.17|   0.00|   0.00|   0.00|   0.00|   1.00|▇▁▁▁▁ |\n|review        |         0|             1|   0.65| 0.09|   0.31|   0.59|   0.65|   0.71|   1.00|▁▃▇▃▁ |\n|projects      |         0|             1|   3.27| 0.58|   2.00|   3.00|   3.00|   4.00|   5.00|▁▇▁▅▁ |\n|tenure        |         0|             1|   6.56| 1.42|   2.00|   5.00|   7.00|   8.00|  12.00|▁▇▇▂▁ |\n|satisfaction  |         0|             1|   0.50| 0.16|   0.00|   0.39|   0.50|   0.62|   1.00|▁▅▇▅▁ |\n|bonus         |         0|             1|   0.21| 0.41|   0.00|   0.00|   0.00|   0.00|   1.00|▇▁▁▁▂ |\n|avg_hrs_month |         0|             1| 184.66| 4.14| 171.37| 181.47| 184.63| 187.73| 200.86|▁▆▇▂▁ |\n:::\n:::\n\n\n- There is no missing data in the data set.\n- Employees are involved between 2 to 5 projects\n- Employees have been at the company between 2 to 12 years, with an average of 6.5 years\n- The average satisfaction rate in 50.41% for all employees\n- The average worked hours per month ranged from 171.37 to 200.86 hours\n- There are some data types that need to be changed. For example, \"left\" is a character variable. To convert it into a quantity that takes values of zero and one, I'll convert it into a variable of type factor with two levels: No and Yes. Later, I will use as.numeric() to convert the observations to a number, one or two. I then subtract one to get a variable that takes values zero or one and stores it as left.Numeric\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nempl_turnover$department <- as.factor(empl_turnover$department)\nempl_turnover$left<- as.factor(empl_turnover$left)\nempl_turnover$promoted<- as.factor(empl_turnover$promoted)\nempl_turnover$bonus<- as.factor(empl_turnover$bonus)\nempl_turnover$salary<- factor(empl_turnover$salary, levels = c(\"low\", \"medium\", \"high\"))\nempl_turnover$left.Numeric <- as.numeric(as.factor(empl_turnover$left))-1\n\n\nglimpse(empl_turnover)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 9,540\nColumns: 11\n$ department    <fct> operations, operations, support, logistics, sales, IT, a…\n$ promoted      <fct> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ review        <dbl> 0.5775687, 0.7518997, 0.7225484, 0.6751583, 0.6762032, 0…\n$ projects      <int> 3, 3, 3, 4, 3, 2, 4, 4, 4, 3, 4, 3, 3, 3, 3, 3, 4, 4, 3,…\n$ salary        <fct> low, medium, medium, high, high, medium, high, medium, l…\n$ tenure        <dbl> 5, 6, 6, 8, 5, 5, 5, 7, 6, 6, 5, 5, 6, 5, 6, 6, 6, 5, 6,…\n$ satisfaction  <dbl> 0.6267590, 0.4436790, 0.4468232, 0.4401387, 0.5776074, 0…\n$ bonus         <fct> 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,…\n$ avg_hrs_month <dbl> 180.8661, 182.7081, 184.4161, 188.7075, 179.8211, 178.84…\n$ left          <fct> no, no, no, no, no, no, no, no, no, no, no, no, no, no, …\n$ left.Numeric  <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n```\n:::\n:::\n\n\n\n#### **Turnover**\n\nNumber of employees that left the company:\n\nThe overall attrition rate in the company is 29.2%, which means that 2,784 of 9,540 employees have left the company over the past 24 months.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nempl_turnover_left <- single_prop(empl_turnover, var = \"left\", lev = \"yes\")\nsummary(empl_turnover_left)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSingle proportion test (binomial exact)\nData      : empl_turnover \nVariable  : left \nLevel     : yes in left \nConfidence: 0.95 \nNull hyp. : the proportion of yes in left = 0.5 \nAlt. hyp. : the proportion of yes in left not equal to 0.5 \n\n     p    ns     n n_missing    sd    se    me\n 0.292 2,784 9,540         0 0.455 0.005 0.009\n\n   diff    ns p.value  2.5% 97.5%    \n -0.208 2,784  < .001 0.283 0.301 ***\n\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\n#### **Are the employees leaving the different departments at the same rate?**\n\n- The data shows that the IT department has the highest employee turnover rate, followed by logistics and retail. Finance has the lowest rate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nempl_turnover_prop <- empl_turnover %>% \n  tabyl(department, left) %>%\n  adorn_percentages(\"row\") %>%\n  mutate(Perc_empl_left = paste0(round(yes * 100),\"%\"))\n\nkable(empl_turnover_prop,  caption = \"Department vs Attrition\")\n```\n\n::: {.cell-output-display}\nTable: Department vs Attrition\n\n|department  |        no|       yes|Perc_empl_left |\n|:-----------|---------:|---------:|:--------------|\n|admin       | 0.7186761| 0.2813239|28%            |\n|engineering | 0.7117414| 0.2882586|29%            |\n|finance     | 0.7313433| 0.2686567|27%            |\n|IT          | 0.6910112| 0.3089888|31%            |\n|logistics   | 0.6916667| 0.3083333|31%            |\n|marketing   | 0.6970075| 0.3029925|30%            |\n|operations  | 0.7135348| 0.2864652|29%            |\n|retail      | 0.6943543| 0.3056457|31%            |\n|sales       | 0.7148168| 0.2851832|29%            |\n|support     | 0.7115646| 0.2884354|29%            |\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nempl_turnover$reordept <-reorder(empl_turnover$department, empl_turnover$left, \n                                 FUN=function(x) mean(as.numeric(x)))\n\n\nplot_depart <- empl_turnover %>%\nggplot(aes(x = reordept, fill = left)) +\ngeom_bar(position = \"fill\")+\nscale_fill_manual(values=c(\"gray\", \"#2166AC\"))+\nlabs(title = \"Turnover Rate by Department\",\n      y= \" \",\n      x= \" \") +\ncoord_flip() +\n ggpubr::theme_pubclean()+\ntheme(\n    plot.title = element_text(size =9, face = \"bold\", hjust = 0.55),\n    legend.position=\"bottom\")\n\nplot_depart\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\n\n#### **Attrition vs Years at the company**\n\nThe majority of employees that left the organization, had been working for the company between 5 to 8 years, and the proportion steadily declined. \n\n**What does it mean for the organization?** Well,\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n### Tenure vs Turnover\n\nempl_turnover %>%\ngroup_by(tenure, left)%>%\nggplot(aes(x = tenure, fill = left)) +\ngeom_histogram(bins = 30L) +\n\nscale_fill_manual(values=c(\"gray\", \"#2166AC\"))+\n\n ggpubr::theme_pubclean()+\n\n\n  labs( x= \"Years at the Company\",\n        y= \"Number of Employees\",\n        title = \"Attrition vs Number of Years Working at the Company\")+\n\ntheme(plot.title = element_text(size =12, face = \"bold\", hjust = 0.45),\nlegend.position=\"bottom\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-7-1.png){width=1440}\n:::\n:::\n\n\n\n\n#### **Do the number of projects employees are involved in and the number of hours per month worked matter in their retention?**\n\nYes, there is a high attrition rate in employees that:\n- Are involved in less than three projects \n- Tend to work ~184 hours per month (assuming a five days work week- 8 hours each)\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-1.png){width=1440}\n:::\n:::\n\n\n\n#### **Attrition vs Promotion, Bonus and Salary**\n\nMost employees are in the medium salary tier, with the rest evenly split between low and high salaries. However, this variable is no significant impact on the turnover status of the employee. Likewise, whether or not an employee received a bonus is not statistically significant on the decision to stay or leave the company.\n\nThe promotion variable shows a higher proportion of employees had stayed with the organization if they had received a promotion.\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n#### **Employee Satisfaction and Review score**\n\n- Employees tend to have lower satisfaction ratings as performance scores increase across employees. As the chart below shows, this feature is more appreciable for employees who have left the company in the last 24 months.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_rev_sat_left<- empl_turnover %>% \n  ggplot(aes(x=review,y= satisfaction, color=left)) +\n  geom_point(alpha=0.16) + \n  geom_smooth(method=lm,se=FALSE)+\n  facet_wrap(~department, ncol=4)+\n   ggpubr::theme_pubclean()+\n   labs (x = \"Review\", \n         y = \"Satisfaction Level\",\n         title= \"\") +\n  theme(\n          strip.background= element_rect(fill= \"white\", linetype = \"blank\"),\n          strip.text = element_text(color= \"black\", face= \"bold\"),\n          strip.text.x = element_text(face = \"bold\", size= 10),\n          \n          plot.title = element_text(size =9, face = \"bold\", hjust = 0.55),\n          plot.title.position = \"plot\")+\n          scale_color_manual(values=c(\"gray\", \"#2166AC\"))\n\n\n\nplot_rev_sat_left\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-1.png){width=775.68}\n:::\n:::\n\n\n## 4. The Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames(empl_turnover)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"department\"    \"promoted\"      \"review\"        \"projects\"     \n [5] \"salary\"        \"tenure\"        \"satisfaction\"  \"bonus\"        \n [9] \"avg_hrs_month\" \"left\"          \"left.Numeric\"  \"reordept\"     \n```\n:::\n:::\n\n\n#### Estimation of a First GLM\n\n\n\n\n```{.r .cell-code}\nfist_model <- glm(left ~ department+ promoted+ review+ projects+ salary+ tenure + satisfaction+ bonus+ avg_hrs_month,\n                  family = binomial(link = \"probit\"), data = empl_turnover)\n\nstargazer(fist_model, type = \"html\", style = \"apsr\")\n```\n\n\n<table style=\"text-align:center\"><tr><td colspan=\"2\" style=\"border-bottom: 1px solid black\"></td></tr><tr><td style=\"text-align:left\"></td><td>left</td></tr>\n<tr><td colspan=\"2\" style=\"border-bottom: 1px solid black\"></td></tr><tr><td style=\"text-align:left\">departmentengineering</td><td>0.008</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.077)</td></tr>\n<tr><td style=\"text-align:left\">departmentfinance</td><td>-0.048</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.097)</td></tr>\n<tr><td style=\"text-align:left\">departmentIT</td><td>0.072</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.100)</td></tr>\n<tr><td style=\"text-align:left\">departmentlogistics</td><td>0.053</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.099)</td></tr>\n<tr><td style=\"text-align:left\">departmentmarketing</td><td>0.031</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.084)</td></tr>\n<tr><td style=\"text-align:left\">departmentoperations</td><td>-0.020</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.077)</td></tr>\n<tr><td style=\"text-align:left\">departmentretail</td><td>0.070</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.076)</td></tr>\n<tr><td style=\"text-align:left\">departmentsales</td><td>-0.004</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.075)</td></tr>\n<tr><td style=\"text-align:left\">departmentsupport</td><td>0.018</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.085)</td></tr>\n<tr><td style=\"text-align:left\">promotedYes</td><td>-0.336<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.090)</td></tr>\n<tr><td style=\"text-align:left\">review</td><td>6.474<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.206)</td></tr>\n<tr><td style=\"text-align:left\">projects</td><td>-0.039</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.025)</td></tr>\n<tr><td style=\"text-align:left\">salarymedium</td><td>0.049</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.041)</td></tr>\n<tr><td style=\"text-align:left\">salaryhigh</td><td>0.012</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.052)</td></tr>\n<tr><td style=\"text-align:left\">tenure</td><td>-0.016</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.049)</td></tr>\n<tr><td style=\"text-align:left\">satisfaction</td><td>1.474<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.107)</td></tr>\n<tr><td style=\"text-align:left\">bonusYes</td><td>-0.033</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.035)</td></tr>\n<tr><td style=\"text-align:left\">avg_hrs_month</td><td>0.045<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.017)</td></tr>\n<tr><td style=\"text-align:left\">Constant</td><td>-13.745<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(2.802)</td></tr>\n<tr><td style=\"text-align:left\">N</td><td>9,540</td></tr>\n<tr><td style=\"text-align:left\">Log Likelihood</td><td>-5,174.597</td></tr>\n<tr><td style=\"text-align:left\">AIC</td><td>10,387.190</td></tr>\n<tr><td colspan=\"2\" style=\"border-bottom: 1px solid black\"></td></tr><tr><td colspan=\"2\" style=\"text-align:left\"><sup>*</sup>p < .1; <sup>**</sup>p < .05; <sup>***</sup>p < .01</td></tr>\n</table>\n\n\n#### **A Scaled Coefficient Plot**\n\nThe graph below shows the chosen predictors are deemed important in the decision to leave the company, by conventional standards, as all have a very low probability of no relationship/zero slopes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nempl_turnover %>%\n    mutate(review = scale(review), satisfaction = scale(satisfaction), tenure = scale(tenure), avg_hrs_month = scale(avg_hrs_month)) %>%\n  \n    glm(left ~ promoted + review+ satisfaction + avg_hrs_month,\n        family = binomial(link = \"probit\"), data = .) %>%\n    plot_summs(., inner_ci_level = 0.95)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(fist_model$coefficients)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          (Intercept) departmentengineering     departmentfinance \n         1.072936e-06          1.008184e+00          9.532048e-01 \n         departmentIT   departmentlogistics   departmentmarketing \n         1.075123e+00          1.054431e+00          1.031526e+00 \n departmentoperations      departmentretail       departmentsales \n         9.803633e-01          1.073022e+00          9.962452e-01 \n    departmentsupport           promotedYes                review \n         1.018490e+00          7.149125e-01          6.483703e+02 \n             projects          salarymedium            salaryhigh \n         9.614144e-01          1.049773e+00          1.012216e+00 \n               tenure          satisfaction              bonusYes \n         9.839700e-01          4.367494e+00          9.674300e-01 \n        avg_hrs_month \n         1.046350e+00 \n```\n:::\n:::\n\n\nAll else equal,\n\n- \n\nThe confidence intervals for the odds-ratios\n\n\n::: {.cell}\n\n```{.r .cell-code}\nexp(confint(fist_model))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                             2.5 %       97.5 %\n(Intercept)           4.479402e-09 2.555836e-04\ndepartmentengineering 8.680227e-01 1.172381e+00\ndepartmentfinance     7.868521e-01 1.154481e+00\ndepartmentIT          8.847389e-01 1.306345e+00\ndepartmentlogistics   8.669936e-01 1.282205e+00\ndepartmentmarketing   8.761377e-01 1.215477e+00\ndepartmentoperations  8.440660e-01 1.140018e+00\ndepartmentretail      9.243293e-01 1.247159e+00\ndepartmentsales       8.604869e-01 1.154899e+00\ndepartmentsupport     8.626117e-01 1.203414e+00\npromotedYes           5.977079e-01 8.514388e-01\nreview                4.366161e+02 9.657228e+02\nprojects              9.162055e-01 1.008823e+00\nsalarymedium          9.681911e-01 1.138699e+00\nsalaryhigh            9.145515e-01 1.120379e+00\ntenure                8.944537e-01 1.082440e+00\nsatisfaction          3.533664e+00 5.406458e+00\nbonusYes              9.033618e-01 1.035781e+00\navg_hrs_month         1.012700e+00 1.081136e+00\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nfit.BT <- rpart(left ~ promoted + review + projects + satisfaction + avg_hrs_month,\n    data = empl_turnover, method = \"class\")\nrpart.plot(fit.BT)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n## 5. Conclusion and Recomendations\n\n\n## 6. References",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}